### PR TITLE
Add ForceDiagram Scale to RhinoForms

### PR DESCRIPTION
**Pull request by ricardoavelino**
This is useful for visualising which is the scale and also to edit it in the same nice form.

### CODE REVIEW

**Comment by Licini** [comment]
> This is useful for visualising which is the scale and also to edit it in the same nice form.

Alright got few questions before we can merge @ricardoavelino :
1. Does this factor serve the same purpose of `scale.force` option under `formObject` ?
2. Could this factor be put under settings attributes at: https://github.com/BlockResearchGroup/compas_ags/blob/48d23a7373beef0c367a4dd07a1659d7edf0b9c0/src/compas_ags/rhino/forceobject.py#L16-L37
Because in that way the settings form will be able to automatically handle it without adding a lot of changes

**Comment by ricardoavelino** [comment]
The purpose is different. This scales the force diagram (it is a proper scale factor). It is stored as a property: ForceObject.scale since it is part of the data that must be stored to the scene... We can leave @brgcode decide if it is worth to change it to the settings dictionary to add it to the RhinoForms, but it seems a bit of too much work for now. This scale can still be accessed via the command: `force_scale`.

**Comment by brgcode** [comment]
is this supposed to be merged or is there ore work to be done?

**Comment by ricardoavelino** [comment]
I guess for V 1.0 we will not include this. the user can nicely change the scale in the appropriate function and also "get to know" the scale by using the command "AGS_edge_information". So I will just close this.

**Pull request closed without merging**
